site_name: Сестра готовит – быстрые и интуитивные рецепты
copyright: "&copy; 2024 Сестра готовит"
theme:
  name: material
  logo: images/favicon/sister-logo.png
  favicon: images/favicon/fav.ico
  font:
    text: Montserrat
  features:
    - search.suggest
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.footer
  language: ru
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
  - tags
  - glightbox
  - blog:
      post_date_format: medium
      post_url_format: "{file}"
      post_excerpt: required
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html 
  - smarty
  - tables
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys # usage ++ctrl+alt+delete++
  - pymdownx.mark # usage ==mark me==
  - pymdownx.tilde # usage ~~Delete me~~
  - pymdownx.tabbed # usage https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Понравилось?
      ratings:
        - icon: material/heart
          name: Да, всё супер!
          data: 1
          note: >-
            Спасибо за отзыв!
        - icon: material/heart-broken
          name: Есть что улучшить
          data: 0
          note: >- 
            Спасибо за отзыв!
  social:
    - icon: fontawesome/brands/x-twitter 
      link: https://twitter.com/vervedel
  consent:
    title: Согласие на использование файлов cookie 
    description: >- 
      Мы используем файлы cookie для распознавания ваших повторных посещений и предпочтений, а также
      для оценки эффективности нашего сайта и того, находят ли пользователи то, что ищут. 
      С вашего согласия вы помогаете нам сделать наш сайт лучше.
    actions:
      - accept
      - reject
      - manage 

nav:
  - Завтраки:
    - breakfast/index.md
    - Блюда из яиц:
      - breakfast/fried-eggs.md
      - breakfast/omelet.md
      - breakfast/scrambled-eggs.md
      - breakfast/pashot.md
    - Блины и оладьи:   
      - breakfast/creppe.md
      - breakfast/pancakes.md
      - breakfast/ovsyanushek.md
    - Каши:
      - breakfast/oat-porridge.md
      - breakfast/polenta.md
    - breakfast/toast-wth-avocado-and-pashot.md
    - breakfast/toast-with-proshuto-and-dried-tomatos.md
    - breakfast/syrniki.md
    - breakfast/cottage-cheese-casserole.md
  - Закуски: 
    - snacks/index.md
    - snacks/humus.md
  - Супы: 
    - soups/index.md
    - soups/borsch.md
    - soups/buckwheat-soup.md
    - soups/chorba.md
    - soups/lapsha.md
    - soups/lental-soup.md
    - soups/rice-soup.md
    - soups/shi.md
    - soups/solyanka.md
  - Горячее: 
    - main-course/index.md
    - main-course/buckweat-with-carrot-and-onion.md
  - Десерты: 
    - dessert/index.md
    - dessert/brauni.md
    - dessert/orange-cake.md
    - dessert/tiramisu.md
  - Выпечка: 
    - pastry/index.md
  - Напитки:
    - drinks/index.md
    - drinks/coffee.md
    - drinks/gluhwein-rot.md
    - drinks/gluhwein-weiss.md
    - drinks/home-limonade.md
    - drinks/tea.md
  - Блог:
    - blog/index.md